### ISSUE TITLE
Error when using djwt with deno 1.4.6

### ISSUE THREAD

**Issue by yeukfei02** [timonson/djwt#36]
```
TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  Payload,
  ~~~~~~~
    at https://deno.land/x/djwt@v1.2/validate.ts:206:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  Handlers,
  ~~~~~~~~
    at https://deno.land/x/djwt@v1.2/validate.ts:207:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  JwtObject,
  ~~~~~~~~~
    at https://deno.land/x/djwt@v1.2/validate.ts:208:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  JwtValidation,
  ~~~~~~~~~~~~~
    at https://deno.land/x/djwt@v1.2/validate.ts:209:3

TS1205 [ERROR]: Re-exporting a type when the '--isolatedModules' flag is provided requires using 'export type'.
  Validation,
  ~~~~~~~~~~
    at https://deno.land/x/djwt@v1.2/validate.ts:210:3
```

any existing lib version can use? or need to wait for fix?
I am using `oak` framework, thanks.

**Comment by timonson** [comment]
The latest version should work.

**Comment by yeukfei02** [comment]
ok use `v1.7` no error for now.
thanks.
