### ISSUE TITLE
djvt 1.9 create.ts  failed: 404 Not Found

### ISSUE THREAD

**Issue by YuriyTigiev** [timonson/djwt#38]
Hello, 

Issues with using a djwt 1.9

Download https://deno.land/x/djwt/validate.ts
Download https://deno.land/x/djwt/create.ts
Warning Implicitly using latest version (v1.9) for https://deno.land/x/djwt/validate.ts
Download https://deno.land/x/djwt@v1.9/validate.ts
Warning Implicitly using latest version (v1.9) for https://deno.land/x/djwt/create.ts
Download https://deno.land/x/djwt@v1.9/create.ts
error: Import 'https://deno.land/x/djwt@v1.9/validate.ts' failed: 404 Not Found
    at file:///C:/Users/yuriy/OneDrive/Documents/GitHub/deno_rest/deps.ts:27:0

**Comment by timonson** [comment]
Please use `https://deno.land/x/djwt@v1.9/mod.ts` from now on because `create.ts` and `validate.ts` don't exist anymore.

**Comment by YuriyTigiev** [comment]
Another error

```
import * as yup from "https://cdn.skypack.dev/yup";

export {
  AES,
  encode,
} from "https://deno.land/x/god_crypto/mod.ts";
export {
  Application,
  Router,
  send,
  Context,
  Status,
  isHttpError,
  helpers,
} from "https://deno.land/x/oak/mod.ts";
export type {
  RouterContext,
} from "https://deno.land/x/oak/mod.ts";
export { config as dotEnv } from "https://deno.land/x/dotenv/mod.ts";
export {
  handlers,
  getLogger,
  setup,
} from "https://deno.land/std/log/mod.ts";
export { MongoClient, ObjectId } from "https://deno.land/x/mongo/mod.ts";
export { oakCors } from "https://raw.githubusercontent.com/tajpouria/cors/master/mod.ts"; // Currently using fork version to support deno 1.4.0
export { validateJwt } from "https://deno.land/x/djwt@v1.9/mod.ts";
export type {
  Jose,
  Payload,
} from "https://deno.land/x/djwt@v1.9/mod.ts";
export {
  makeJwt,
  setExpiration,
} from "https://deno.land/x/djwt@v1.9/mod.ts";
export { yup };

```



```
Check file:///C:/Users/yuriy/OneDrive/Documents/GitHub/deno_rest/deps.ts
error: TS2305 [ERROR]: Module '"https://deno.land/x/djwt@v1.9/mod.ts"' has no exported member 'validateJwt'.
export { validateJwt } from "https://deno.land/x/djwt@v1.9/mod.ts";
         ~~~~~~~~~~~
    at file:///C:/Users/yuriy/OneDrive/Documents/GitHub/deno_rest/deps.ts:27:10

TS2305 [ERROR]: Module '"https://deno.land/x/djwt@v1.9/mod.ts"' has no exported member 'Jose'.
  Jose,
  ~~~~
    at file:///C:/Users/yuriy/OneDrive/Documents/GitHub/deno_rest/deps.ts:29:3

TS2305 [ERROR]: Module '"https://deno.land/x/djwt@v1.9/mod.ts"' has no exported member 'makeJwt'.
  makeJwt,
  ~~~~~~~
    at file:///C:/Users/yuriy/OneDrive/Documents/GitHub/deno_rest/deps.ts:33:3

TS2305 [ERROR]: Module '"https://deno.land/x/djwt@v1.9/mod.ts"' has no exported member 'setExpiration'.
  setExpiration,
  ~~~~~~~~~~~~~
    at file:///C:/Users/yuriy/OneDrive/Documents/GitHub/deno_rest/deps.ts:34:3

Found 4 errors.
```
