### ISSUE TITLE
Cannot find name 'HmacKeyAlgorithm'

### ISSUE THREAD

**Issue by tomekrozalski** [timonson/djwt#62]
Hi. I try it as simplest as I can:

```
import { create } from "https://deno.land/x/djwt@v2.4/mod.ts";

const key = await crypto.subtle.generateKey(
  { name: "HMAC", hash: "SHA-512" },
  true,
  ["sign", "verify"]
);

const jwt = await create({ alg: "HS512", typ: "JWT" }, { foo: "bar" }, key);
```

but get errors in console:

```
error: TS2304 [ERROR]: Cannot find name 'HmacKeyAlgorithm'.
): algorithm is HmacKeyAlgorithm | RsaHashedKeyAlgorithm {
                ~~~~~~~~~~~~~~~~
    at https://deno.land/x/djwt@v2.4/algorithm.ts:24:17

TS2304 [ERROR]: Cannot find name 'RsaHashedKeyAlgorithm'.
): algorithm is HmacKeyAlgorithm | RsaHashedKeyAlgorithm {
                                   ~~~~~~~~~~~~~~~~~~~~~
    at https://deno.land/x/djwt@v2.4/algorithm.ts:24:36

TS2304 [ERROR]: Cannot find name 'EcKeyAlgorithm'.
): algorithm is EcKeyAlgorithm {
                ~~~~~~~~~~~~~~
    at https://deno.land/x/djwt@v2.4/algorithm.ts:30:17

TS2339 [ERROR]: Property 'hash' does not exist on type 'KeyAlgorithm'.
        return keyAlgorithm.hash.name === algAlgorithm.hash.name;
                            ~~~~
    at https://deno.land/x/djwt@v2.4/algorithm.ts:47:29

TS2339 [ERROR]: Property 'namedCurve' does not exist on type 'never'.
        return keyAlgorithm.namedCurve === algAlgorithm.namedCurve;
                            ~~~~~~~~~~
    at https://deno.land/x/djwt@v2.4/algorithm.ts:49:29

Found 5 errors.
[E] [daem] app crashed - waiting for file changes before starting ...
```

Any idea what is wrong? I use Deno 1.13.2

**Comment by tomekrozalski** [comment]
Huh, I see the console errors when I write only this line:

```
import * as jwt from "https://deno.land/x/djwt@v2.4/mod.ts";
```

**Comment by grempe** [comment]
I use the following. You might try a similar import. 

```
import { decode, validate } from "https://deno.land/x/djwt@v2.3/mod.ts";
```

**Comment by tomekrozalski** [comment]
@grempe thank you for very quick reply. It helped :)
