### ISSUE TITLE
Cannot create token Uncaught TypeError: Cannot read properties of undefined (reading 'name')

### ISSUE THREAD

**Issue by mrabtikhalid** [timonson/djwt#76]
Hello, I run into a problem, i cant generate a valid token, starting from version >= 2.3,
example:
this is my code
```
import { create } from "https://deno.land/x/djwt@v2.3/mod.ts?s=create";
const jwt = await create({ alg: "HS512", typ: "JWT" }, { foo: "bar" }, "key");
console.log(jwt)
```
and i got this error
```
error: Uncaught TypeError: Cannot read properties of undefined (reading 'name')
    if (key.algorithm.name === algorithm.name) {
                      ^
    at verify (https://deno.land/x/djwt@v2.3/algorithm.ts:32:23)
    at create (https://deno.land/x/djwt@v2.3/mod.ts?s=create:180:7)
    at /test.js:2:19
```
but if i downgrade the library to v2.2 or less, it works

this is my code
```
import { create } from "https://deno.land/x/djwt@v2.2/mod.ts?s=create";
const jwt = await create({ alg: "HS512", typ: "JWT" }, { foo: "bar" }, "key");
console.log(jwt)
```
and i got the response
```
eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJmb28iOiJiYXIifQ.MOpRGi_LKTP15S-PLQ1mxMaCrIPqbItvq_QzNovtancw7ZegFP-S-1sE6j3a8JLu6Wn03tnWjOkHHw13gzsPQw
```

Can I help with something ?

**Comment by timonson** [comment]
We use `CryptoKey` instead of `string` as key since `v2.3`. Look at the README for more details.
